### ISSUE TITLE
TG推送的问题

### ISSUE THREAD

**Issue by AlterGu** [jiegto/Actions_smzdm#2]
tg推送是只要把TG_BOT_TOKEN和TG_USER_ID写到secrets里面就好了吧? 
我这么做了以后会显示"telegram发送通知消息失败！！" , 请问怎么解决

**Comment by jiegto** [comment]
确实是只需要 token 和 ID

建议可以尝试：
1、确认从@BotFather 获取正确的 token，图示中需完整复制
![CleanShot 2020-11-12 at 12 01 32](https://user-images.githubusercontent.com/15905889/98894050-e0ee8600-24de-11eb-80af-bb3176286ec9.jpg)
2、确认从@userinfobot 获取正确的ID
3、确认已经在你创建的 bot 里，发送 /start 进行启用

如果以上还不行，我暂时也想不出问题还可能出现哪里。

**Comment by AlterGu** [comment]
> 3、确认已经在你创建的 bot 里，发送 /start 进行启用

"3、确认已经在你创建的 bot 里，发送 /start 进行启用" 是在@Botfather里面发送吗

**Comment by jiegto** [comment]
不是@BotFather，是你自己创建的用来接受消息的 bot 里面发送。

**Comment by AlterGu** [comment]
> 不是@Botfather，是你自己创建的用来接受消息的 bot 里面发送。

请问这个怎么创建, 我好像没有弄过

**Comment by jiegto** [comment]
网上有很多教程，你随意找一个看下就知道了。例如：https://adao.me/ruanjian/28.html

**Comment by AlterGu** [comment]
谢谢,已经搞定
