### ISSUE TITLE
脚本执行报错（含log）

### ISSUE THREAD

**Issue by Caiiiiii** [jiegto/Actions_smzdm#3]
🔔undefined, 开始!
下载代码完毕
替换变量完毕
(node:2538) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at Main (/home/runner/work/SMZDMActions/SMZDMActions/smzdm_checkin.js:802:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
执行完毕
(node:2526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
    at resolve (/home/runner/work/SMZDMActions/SMZDMActions/sendNotify.js:62:25)
    at new Promise (<anonymous>)
    at serverNotify (/home/runner/work/SMZDMActions/SMZDMActions/sendNotify.js:59:13)
    at Object.sendNotify (/home/runner/work/SMZDMActions/SMZDMActions/sendNotify.js:53:11)
    at start (/home/runner/work/SMZDMActions/SMZDMActions/function/smzdm.js:72:22)
(node:2526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by antsman9** [comment]
🔔什么值得买签到, 开始!

🔔undefined, 开始!
下载代码完毕
替换变量完毕
执行完毕
(node:2487) UnhandledPromiseRejectionWarning: TypeError: desp.replace is not a function
    at resolve (/home/runner/work/SMZDM-BOT/SMZDM-BOT/sendNotify.js:62:25)
    at new Promise (<anonymous>)
    at serverNotify (/home/runner/work/SMZDM-BOT/SMZDM-BOT/sendNotify.js:59:13)
    at Object.sendNotify (/home/runner/work/SMZDM-BOT/SMZDM-BOT/sendNotify.js:53:11)
    at start (/home/runner/work/SMZDM-BOT/SMZDM-BOT/function/smzdm.js:72:22)
(node:2487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2487) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by antsman9** [comment]
> 🔔undefined, 开始!
> 下载代码完毕
> 替换变量完毕
> (node:2538) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
> at Main (/home/runner/work/SMZDMActions/SMZDMActions/smzdm_checkin.js:802:30)
> at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:2538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:2538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 执行完毕
> (node:2526) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of null
> at resolve (/home/runner/work/SMZDMActions/SMZDMActions/sendNotify.js:62:25)
> at new Promise ()
> at serverNotify (/home/runner/work/SMZDMActions/SMZDMActions/sendNotify.js:59:13)
> at Object.sendNotify (/home/runner/work/SMZDMActions/SMZDMActions/sendNotify.js:53:11)
> at start (/home/runner/work/SMZDMActions/SMZDMActions/function/smzdm.js:72:22)
> (node:2526) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:2526) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

我们问题是不是一样？

**Comment by antsman9** [comment]
我这个也是server酱推送的问题吗？

(node:2351) UnhandledPromiseRejectionWarning: TypeError: desp.replace is not a function
    at resolve (/home/runner/work/SMZDM-START/SMZDM-START/sendNotify.js:62:25)
    at new Promise (<anonymous>)
    at serverNotify (/home/runner/work/SMZDM-START/SMZDM-START/sendNotify.js:59:13)
    at Object.sendNotify (/home/runner/work/SMZDM-START/SMZDM-START/sendNotify.js:53:11)
    at start (/home/runner/work/SMZDM-START/SMZDM-START/function/smzdm.js:72:22)
(node:2351) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2351) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jiegto** [comment]
抱歉，我最近其它事务较多，没有时间调试。建议先用 TG 来接收推送。

**Comment by antsman9** [comment]
> 抱歉，我最近其它事务较多，没有时间调试。建议先用 TG 来接收推送。

好的！收到！

**Comment by jiegto** [comment]
因为我自己不用 Server酱 ，水平有限，也没有时间调试，故不再提供 Server酱 相关支持，请见谅
